
name: To Dev Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: .

      - name: Run Unit Tests
        run: make test-all

      - name: Run Pipeline Test
        run: make test-pipeline

      - name: Run Integration Test
        run: make test-integration

      - name: Clean Directory
        run: make clean